### ISSUE TITLE
Embedded Kafka Problems.

### ISSUE THREAD

**Issue by SarpongAbasimi** [embeddedkafka/embedded-kafka-schema-registry#247]
Hey, I am seeing these errors with Embedded Kafka.

```
17:27:02.816 [kafka-scheduler-1] ERROR kafka.server.LogDirFailureChannel - Error while writing to checkpoint file /var/folders/l3/dxb1954d48d5v_lfj71wz7540000gn/T/kafka5845553986696747582/replication-offset-checkpoint
java.io.FileNotFoundException: /var/folders/l3/dxb1954d48d5v_lfj71wz7540000gn/T/kafka5845553986696747582/replication-offset-checkpoint.tmp (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:94)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:92)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:67)
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6(ReplicaManager.scala:1769)
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6$adapted(ReplicaManager.scala:1768)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
	at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:1768)
	at kafka.server.ReplicaManager.$anonfun$startHighWatermarkCheckPointThread$1(ReplicaManager.scala:292)
	at kafka.utils.KafkaScheduler.$anonfun$schedule$2(KafkaScheduler.scala:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
17:27:02.817 [kafka-scheduler-1] ERROR kafka.server.ReplicaManager - [ReplicaManager broker=0] Error while writing to highwatermark file in directory /var/folders/l3/dxb1954d48d5v_lfj71wz7540000gn/T/kafka5845553986696747582
org.apache.kafka.common.errors.KafkaStorageException: Error while writing to checkpoint file /var/folders/l3/dxb1954d48d5v_lfj71wz7540000gn/T/kafka5845553986696747582/replication-offset-checkpoint
Caused by: java.io.FileNotFoundException: /var/folders/l3/dxb1954d48d5v_lfj71wz7540000gn/T/kafka5845553986696747582/replication-offset-checkpoint.tmp (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:94)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:92)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:67)
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6(ReplicaManager.scala:1769)
	at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$6$adapted(ReplicaManager.scala:1768)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
	at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:1768)
	at kafka.server.ReplicaManager.$anonfun$startHighWatermarkCheckPointThread$1(ReplicaManager.scala:292)
	at kafka.utils.KafkaScheduler.$anonfun$schedule$2(KafkaScheduler.scala:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
17:27:02.838 [LogDirFailureHandler] ERROR kafka.log.LogManager - Shutdown broker because all log dirs in /var/folders/l3/dxb1954d48d5v_lfj71wz7540000gn/T/kafka5845553986696747582 have failed

Process finished with exit code 1
```

The documentation does not mention anything about this file path and have no idea how to override this.

```
Caused by: java.io.FileNotFoundException: /var/folders/l3/dxb1954d48d5v_lfj71wz7540000gn/T/kafka5845553986696747582/replication-offset-checkpoint.tmp
 (No such file or directory)
```

Anybody able to help with what is going on?

**Comment by francescopellegrini** [comment]
Hi @SarpongAbasimi, could you please share a minimal piece of code presenting this issue?
Thank you in advance

**Comment by SarpongAbasimi** [comment]
yes @francescopellegrini  I have something like this

```
  override def withFixture(test: NoArgAsyncTest): FutureOutcome = {

    val driverName    = DriverName(container.driverClassName)
    val connectionUrl = ConnectionUrl(container.jdbcUrl)
    val user          = DbUser(container.username)
    val password      = PassWord(container.password)

    (for {
      _ <- DbMigrations
        .migrate[IO](
          ApplicationConfig(
            driverName,
            connectionUrl,
            user,
            password
          )
        )
      test <- IO(test())
    } yield test).unsafeRunSync()
  }

  "Kafka" - {
    "should receive a message event when published" in {

      /**
       * Embedded kafka
       * with schema registry not working -
       * Test passes when a stand alone schema registry is run
       */

      implicit val kafkaConfig = EmbeddedKafkaConfig(kafkaPort = 9092, schemaRegistryPort = 8081)

      withRunningKafka {
        val operationType = NewSubscription
        val organization  = Organization("47Degrees")
        val repository    = Repository("Scala Exercise")

        val config = KafkaConfig(
          Topic("dummyProject"),
          BootstrapServer("localhost:9092"),
          GroupId("publisher"),
          SchemaRegistryUrl("http://localhost:8081"),
          UserName("Ben"),
          Password("password")
        )

        val consumedResult: Stream[IO, CommittableConsumerRecord[IO, String, MessageEvent]] = for {
          producerSerializer <- Stream.eval(
            IO(
              avroSerializer[MessageEvent].using(
                AvroSettings(
                  SchemaRegistryClientSettings[IO](config.schemaRegistryUrl.schemaRegistryUrl)
                )
              )
            )
          )
          producerSettings <- Stream.eval(
            IO.pure(
              ProducerSettings(
                keySerializer = Serializer[IO, String],
                valueSerializer = producerSerializer
              ).withBootstrapServers("localhost:9092")
            )
          )
          producerResource <- Stream.resource(KafkaProducer.resource(producerSettings))
          _ <- Stream.eval(
            KafkaProducerImplementation
              .imp[IO](config, producerResource)
              .publish("1", MessageEvent(operationType, organization, repository))
          )
          _ <- Stream.eval(IO())
          consumerDeserializer <- Stream.eval(
            IO.pure(avroDeserializer[MessageEvent].using(AvroSettings {
              SchemaRegistryClientSettings[IO](config.schemaRegistryUrl.schemaRegistryUrl)
            }))
          )
          consumerSettings <- Stream.eval(
            IO(
              ConsumerSettings[IO, String, MessageEvent](
                keyDeserializer = ConsumerDeserializer[IO, String],
                valueDeserializer = consumerDeserializer
              ).withAutoOffsetReset(AutoOffsetReset.Earliest)
                .withBootstrapServers(config.bootstrapServer.bootstrapServer)
                .withGroupId(config.groupId.groupId)
            )
          )
          consumerResource          <- Stream.resource(KafkaConsumer.resource(consumerSettings))
          consumer                  <- Stream.eval(IO(KafkaConsumerImplementation.imp[IO](config, consumerResource)))
          committableConsumerRecord <- consumer.consume.take(1)
        } yield committableConsumerRecord

        consumedResult
          .map(_.record.value)
          .compile
          .lastOrError
          .asserting { listOfMessageEvent =>
            listOfMessageEvent.operationType shouldBe operationType
            listOfMessageEvent.organization shouldBe organization
            listOfMessageEvent.repository shouldBe repository
          }
      }
    }
  }
}

```

**Comment by SarpongAbasimi** [comment]
This is the test causing the error @francescopellegrini. It passes when I run a separate schema registry container.
when when I use embedded Kafka, I get the error mentioned above.

**Comment by SarpongAbasimi** [comment]
> Hi @SarpongAbasimi, could you please share a minimal piece of code presenting this issue?
> Thank you in advance

Also just to mention I am using `fs2-kafka`
- https://fd4s.github.io/fs2-kafka/docs/consumers

**Comment by francescopellegrini** [comment]
I'm not familiar with fs2-kafka, but I think the issue here is that your testing **asynchronously**, while embedded-kafka stops all of its processes at the end of the `withRunningKafka` clojure.

You need to use something like `unsafeRunSync` inside the clojure to retrieve the message, only then you will be able to assert on it (which could be done after the clojure).

**Comment by SarpongAbasimi** [comment]
Thanks @francescopellegrini.

I am not sure if I understand what you mean by `clojure` but the assertion is being done in the `withRunningKafka`

**Comment by francescopellegrini** [comment]
`withRunningKafka` function cannot return an async computation, like `IO`, because it will immediately stop all containers, thus making impossibile to check the result.

**Comment by SarpongAbasimi** [comment]
sure, thank you very much @francescopellegrini. I will have a look at this again tomorrow
